In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
     

df = sns.load_dataset('iris')
     

df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [2]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X = df.drop('species',axis = 1)
y = df['species']
     
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.33, random_state=42)

In [5]:
from sklearn.neighbors import KNeighborsClassifier
     
model_knn = KNeighborsClassifier(n_neighbors=1)
     
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [6]:
model_knn.score(X_test,y_test)

0.98

In [7]:
from sklearn.svm import SVC
     
model_svm = SVC(gamma= 'auto')
     
model_svm.fit(X_train,y_train)

SVC(gamma='auto')

In [8]:
model_svm.score(X_test, y_test)

1.0

In [9]:
from sklearn.model_selection import GridSearchCV

In [10]:
classifier = GridSearchCV((model_svm),{
    'C': [1,10,20,30],
    'kernel': ['rbf','linear']
}, cv=5)

In [13]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [14]:
classifier.cv_results_

{'mean_fit_time': array([0.01676221, 0.0047173 , 0.00448346, 0.00359917, 0.00441589,
        0.00517325, 0.00586576, 0.00636525]),
 'std_fit_time': array([0.00809027, 0.00049517, 0.00033582, 0.00027955, 0.00066929,
        0.00070302, 0.0020085 , 0.00109139]),
 'mean_score_time': array([0.0088696 , 0.00450416, 0.00324526, 0.00278864, 0.00364909,
        0.00416999, 0.00398107, 0.00456882]),
 'std_score_time': array([0.00502426, 0.00069   , 0.00024739, 0.00018571, 0.00042743,
        0.0006188 , 0.0003747 , 0.00046284]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [15]:
results = pd.DataFrame(classifier.cv_results_)

In [16]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [17]:
from sklearn.model_selection import RandomizedSearchCV

In [31]:
classifier = RandomizedSearchCV((model_svm),{
    'C': [1,10,20,30],
    'kernel': ['rbf','linear']
}, n_iter=4, cv=5)

In [32]:
classifier.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [33]:
results = pd.DataFrame(classifier.cv_results_)

In [34]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1       linear         0.980000
1       20          rbf         0.966667
2       30          rbf         0.960000
3       30       linear         0.960000